(function(){
  'use strict';
  const game=window.GPGeneralArcade,items=game.items,level=game.level;
  const $=s=>document.querySelector(s),shuffle=a=>[...a].sort(()=>Math.random()-.5);
  $('#back').href=game.returnUrl;$('#badge').textContent=`Level ${level.toUpperCase()} · Week ${game.week}`;
  const characters=[
    {id:'gerry',name:'Gerry',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/gerry-standing-uniform-v2.png?asset=03412bbef0e1',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/gerry-winning-uniform-v2.png?asset=7e5b4289173a'},
    {id:'penny',name:'Penny',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/penny-standing.png?asset=03233aaaa078',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/penny-winning.png?asset=bfb348615edf'},
    {id:'syd',name:'Syd',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/syd-standing.png?asset=a7f964bb56ea',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/syd-winning.png?asset=d4824d38e55d'},
    {id:'ria',name:'Ria',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/ria-standing.png?asset=c6c021cd49ff',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/ria-winning.png?asset=bedec5f2c553'},
    {id:'coover',name:'Coover',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/coover-standing.png?asset=9f889cd918d0',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/coover-winning.png?asset=eebdc8f3a489'},
    {id:'wanda',name:'Wanda',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/wanda-standing.png?asset=4a9c33c8d0a7',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/wanda-winning.png?asset=8f19ed34b24b'},
    {id:'don',name:'Don',standing:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/don-standing-uniform-v2.png?asset=28e09587625d',winner:'https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/characters/don-winning-uniform-v2.png?asset=1d4c1335172c'}
  ];
  const END=29,events={4:{icon:'⭐',title:'Star Boost!',copy:'Shine forward 3 spaces!',move:3},7:{icon:'🎁',title:'Glow Gift!',copy:'Your GP Friend is glowing!',glow:true},10:{icon:'💣',title:'Bomb Bounce!',copy:'Boom! Hop back 2 spaces.',move:-2},16:{icon:'⭐',title:'Star Boost!',copy:'Shine forward 2 spaces!',move:2},19:{icon:'🔄',title:'Roll Again!',copy:'Take another turn!',again:true},22:{icon:'💣',title:'Bomb Bounce!',copy:'Boom! Hop back 3 spaces.',move:-3},25:{icon:'🎁',title:'Glow Gift!',copy:'Your GP Friend is glowing!',glow:true},27:{icon:'⭐',title:'Final Star!',copy:'Almost there—jump ahead 2 spaces!',move:2}};
  let pos=0,turn=0,locked=true,selected=null,audioCtx=null,audioOutput=null,muted=false,giftCount=0,activeQuestionSpeech='';
  const EFFECT_VOLUME=2.65;
  function audio(){const AudioEngine=window.AudioContext||window.webkitAudioContext;if(!AudioEngine)return null;if(!audioCtx){audioCtx=new AudioEngine();audioOutput=audioCtx.createGain();const limiter=audioCtx.createDynamicsCompressor();limiter.threshold.value=-12;limiter.knee.value=12;limiter.ratio.value=8;limiter.attack.value=.003;limiter.release.value=.16;audioOutput.gain.value=EFFECT_VOLUME;audioOutput.connect(limiter).connect(audioCtx.destination)}if(audioCtx.state==='suspended')audioCtx.resume().catch(()=>{});return audioCtx}
  function setMuted(value){muted=value;if(audioOutput)audioOutput.gain.setTargetAtTime(muted?0:EFFECT_VOLUME,audioCtx.currentTime,.015);const button=$('#sound');button.textContent=muted?'🔇':'🔊';button.setAttribute('aria-label',muted?'Turn sound on':'Turn sound off')}
  function note(frequency,duration=.12,type='sine',delay=0,volume=.11,endFrequency=frequency){if(muted)return;const ctx=audio();if(!ctx)return;const oscillator=ctx.createOscillator(),gain=ctx.createGain(),start=ctx.currentTime+delay;oscillator.type=type;oscillator.frequency.setValueAtTime(frequency,start);oscillator.frequency.exponentialRampToValueAtTime(Math.max(35,endFrequency),start+duration);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.012);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);oscillator.connect(gain).connect(audioOutput);oscillator.start(start);oscillator.stop(start+duration+.03)}
  function noise(duration=.14,delay=0,volume=.06,frequency=900){if(muted)return;const ctx=audio();if(!ctx)return;const length=Math.max(1,Math.floor(ctx.sampleRate*duration)),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*(1-i/length);const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain(),start=ctx.currentTime+delay;source.buffer=buffer;filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.8;gain.gain.setValueAtTime(volume,start);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);source.connect(filter).connect(gain).connect(audioOutput);source.start(start)}
  const sfx={
    dice(){[0,.09,.18,.29,.41,.54,.68,.82].forEach((delay,index)=>{noise(.055,delay,.075,620+index*35);note(index%2?185:235,.065,'triangle',delay,.085,index%2?150:195)})},
    diceLand(value=1){noise(.07,0,.065,920);note(360+value*34,.12,'triangle',0,.13,430+value*38);note(690+value*42,.19,'sine',.07,.12,760+value*45)},
    jump(){note(250,.09,'triangle',0,.07,390);note(520,.055,'sine',.07,.045,570)},
    correct(){[523,659,784].forEach((f,i)=>note(f,.16,'sine',i*.075,.08,f*1.03))},
    wrong(){note(240,.18,'triangle',0,.08,150);note(145,.22,'sawtooth',.12,.045,95)},
    star(){[660,880,1100,1320].forEach((f,i)=>note(f,.18,'sine',i*.065,.065,f*1.08))},
    bomb(){noise(.32,0,.14,180);note(150,.35,'sawtooth',0,.12,48);note(85,.4,'square',.08,.055,42)},
    gift(){[392,523,659,784].forEach((f,i)=>note(f,.32,'sine',i*.09,.07,f))},
    rainbow(){[523,659,784,988,1175,1319].forEach((f,i)=>note(f,.25,'sine',i*.065,.075,f*1.04));noise(.16,.34,.045,2200)},
    again(){[330,440,550,440,660].forEach((f,i)=>note(f,.11,'triangle',i*.055,.065,f*1.05))},
    win(){[523,659,784,1047,784,1047,1319].forEach((f,i)=>note(f,.28,'sine',i*.11,.09,f*1.02));noise(.18,.58,.045,1900)},
    event(icon){if(icon==='⭐')this.star();else if(icon==='💣')this.bomb();else if(icon==='🎁')this.gift();else this.again()}
  };
  function place(i){const row=Math.floor(i/6),offset=i%6;return{row:5-row,col:row%2===0?offset+1:6-offset}}
  function render(){const board=$('#board'),eventClasses={'🎁':'event-gift','💣':'event-bomb','🔄':'event-again','⭐':'event-star'};let ordinaryNumber=0;board.innerHTML='<svg class="route-line" viewBox="0 0 600 500" preserveAspectRatio="none" aria-hidden="true"><path class="route-outline" d="M50 450 L500 450 C570 450 570 350 500 350 L100 350 C30 350 30 250 100 250 L500 250 C570 250 570 150 500 150 L100 150 C30 150 30 50 100 50 L550 50"/><path class="route-path" d="M50 450 L500 450 C570 450 570 350 500 350 L100 350 C30 350 30 250 100 250 L500 250 C570 250 570 150 500 150 L100 150 C30 150 30 50 100 50 L550 50"/></svg>';for(let i=0;i<=END;i++){const event=events[i],p=place(i),cell=document.createElement('div'),eventClass=event?` ${eventClasses[event.icon]||''}`:'';cell.className=`cell${event?' special':''}${eventClass}${i===0?' start-space':''}${i===END?' finish':''}`;cell.style.gridRow=p.row;cell.style.gridColumn=p.col;if(i===0){cell.innerHTML='<span class="start-label">START</span>';cell.setAttribute('aria-label','Start space')}else if(i===END){cell.innerHTML='<span class="finish-wrap"><img class="finish-trophy" src="https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/general-arcade/assets/trophy-3d-v1.webp?asset=5189718f8f4f" alt=""><strong class="finish-label">FINISH</strong></span>';cell.setAttribute('aria-label','Golden trophy finish')}else if(event){cell.innerHTML=`<span class="event-icon" aria-label="${event.title}">${event.icon}</span>`;cell.setAttribute('aria-label',event.title)}else{ordinaryNumber++;cell.innerHTML=`<span class="space-number">${ordinaryNumber}</span>`;cell.setAttribute('aria-label',`Space ${ordinaryNumber}`)}if(i===pos&&selected){const token=document.createElement('img');token.src=selected.standing;token.className=`token${giftCount>=1?' gift-glow':''}${giftCount>=2?' rainbow-gift':''}`;token.alt=`${selected.name} on the board`;cell.append(token);if(giftCount>=2){const sparkles=document.createElement('span');sparkles.className='gift-sparkles';sparkles.textContent='✨ 🌈 ✨';cell.append(sparkles)}}board.append(cell)}$('#progress').style.width=`${Math.round(pos/END*100)}%`}
  function buildCharacterPicker(){const grid=$('#characterGrid');grid.innerHTML='';characters.forEach(character=>{const button=document.createElement('button');button.type='button';button.className='character-choice';button.dataset.character=character.id;button.innerHTML=`<img src="${character.standing}" alt="${character.name}, standing in original clothes"><span>${character.name}</span>`;button.onclick=()=>selectCharacter(character,button);grid.append(button)})}
  function selectCharacter(character,button){audio();sfx.correct();selected=character;document.querySelectorAll('.character-choice').forEach(el=>el.classList.toggle('selected',el===button));$('#start').disabled=false;$('#playerThumb').src=character.standing;$('#playerThumb').alt=character.name;$('#playerName').textContent=character.name;$('#finishPreview').src=character.winner;$('#finishPreview').alt=`${character.name} winning pose`;game.say(`${character.name} is ready!`);render()}
  function move(target,done){target=Math.max(0,Math.min(target,END));if(target===pos)return done();const direction=target>pos?1:-1;const step=()=>{pos+=direction;sfx.jump();render();if(pos===target)setTimeout(done,220);else setTimeout(step,210)};step()}
  const dieTransforms={1:'rotateX(0deg) rotateY(0deg)',2:'rotateX(-90deg) rotateY(0deg)',3:'rotateX(0deg) rotateY(-90deg)',4:'rotateX(0deg) rotateY(90deg)',5:'rotateX(90deg) rotateY(0deg)',6:'rotateX(0deg) rotateY(180deg)'};
  function showDie(value){$('#diceCube').style.transform=dieTransforms[value]||dieTransforms[1];$('#die').setAttribute('aria-label',value?`Die showing ${value}`:'Roll the die')}
  function unlock(message='Great! Roll again.'){locked=false;$('#die').disabled=false;$('#info').innerHTML=`<strong>${message}</strong>`}
  function win(){locked=true;const winner=$('#finishCharacter');winner.src=selected.winner;winner.alt=`${selected.name} celebrating`;winner.classList.toggle('gift-glow',giftCount>=1);winner.classList.toggle('rainbow-gift',giftCount>=2);$('#finishMessage').textContent=`${selected.name} reached the golden finish!`;$('#finish').classList.toggle('rainbow-finish',giftCount>=2);$('#finish').hidden=false;sfx.win();setTimeout(()=>game.say(`${selected.name} reached the finish! Amazing adventure!`),520)}
  function resolve(){if(pos>=END)return win();const event=events[pos];if(!event)return unlock();let eventTitle=event.title,eventCopy=event.copy;if(event.glow){giftCount++;if(giftCount===1){eventTitle='Golden Glow Gift!';eventCopy='Your GP Friend will glow until the finish!'}else{eventTitle='Rainbow Sparkle Gift!';eventCopy='A rainbow sparkle trail will follow your friend!'}}$('#eventIcon').textContent=event.icon;$('#eventTitle').textContent=eventTitle;$('#eventCopy').textContent=eventCopy;$('#event').hidden=false;if(event.glow&&giftCount>=2)sfx.rainbow();else sfx.event(event.icon);render();setTimeout(()=>game.say(`${eventTitle} ${eventCopy}`),220);setTimeout(()=>{$('#event').hidden=true;if(event.move)move(pos+event.move,()=>pos>=END?win():unlock('What a surprise! Roll again.'));else unlock(event.again?'Bonus roll! Tap the die again.':'Challenge cleared! Roll again.')},1500)}
  function choicesFor(answer){const count=level==='a'?2:level==='b'?3:4;return shuffle([answer,...shuffle(items.filter(x=>x!==answer)).slice(0,Math.min(count-1,items.length-1))])}
  function challenge(){
    if(pos>=END)return win();
    const answer=items[turn%items.length];
    const displayedQuestion=level==='a'?`Which picture shows ${answer.label}?`:answer.sentence;
    activeQuestionSpeech=level==='a'?`Find ${answer.label}.`:answer.sentence;
    $('#prompt').textContent=displayedQuestion;
    const box=$('#choices');
    box.innerHTML='';
    choicesFor(answer).forEach(entry=>{
      const button=document.createElement('button');
      button.className='choice';
      button.innerHTML=`<img src="${entry.image}" alt="${entry.label}"><strong>${entry.label}</strong>`;
      button.onclick=()=>{
        if(entry!==answer){button.classList.remove('wrong');void button.offsetWidth;button.classList.add('wrong');sfx.wrong();return}
        button.classList.add('correct');sfx.correct();setTimeout(()=>game.say(answer.sentence),170);turn++;setTimeout(()=>{$('#question').hidden=true;resolve()},650)
      };
      box.append(button)
    });
    $('#question').hidden=false;
    game.say(activeQuestionSpeech)
  }
  $('#die').onclick=()=>{if(locked||!selected)return;locked=true;$('#die').disabled=true;sfx.dice();const cube=$('#diceCube');cube.style.transform='';cube.classList.add('rolling');$('#info').innerHTML='<strong>Rolling…</strong>';const roll=1+Math.floor(Math.random()*6);setTimeout(()=>{cube.classList.remove('rolling');showDie(roll);sfx.diceLand(roll);$('#info').innerHTML=`<strong>Jump ${roll} space${roll===1?'':'s'}!</strong>`;move(pos+roll,()=>setTimeout(()=>events[pos]?resolve():challenge(),260))},1000)};
  function reset(){pos=0;turn=0;giftCount=0;locked=false;$('#finish').hidden=true;$('#finish').classList.remove('rainbow-finish');unlock('Tap the die!');render()}
  function openPicker(){locked=true;$('#finish').hidden=true;$('#playPane').hidden=true;$('#playPane').style.display='none';$('#pickerPane').hidden=false;$('#pickerPane').style.display='block';$('#start').disabled=!selected;render()}
  $('#repeatQuestion').onclick=()=>{if(activeQuestionSpeech){audio();game.say(activeQuestionSpeech)}};
  $('#start').onclick=()=>{if(!selected)return;audio();sfx.star();$('#pickerPane').hidden=true;$('#pickerPane').style.display='none';$('#playPane').hidden=false;$('#playPane').style.display='flex';reset()};$('#again').onclick=()=>{audio();reset()};$('#change').onclick=openPicker;$('#changePlayer').onclick=openPicker;$('#sound').onclick=()=>{audio();setMuted(!muted);if(!muted){sfx.correct();setTimeout(()=>game.say('Sound is on!'),180)}};document.addEventListener('pointerdown',audio,{once:true,capture:true});buildCharacterPicker();render();
})();
