(() => {
  const pictures=window.WeeklyGames.items.map(item=>({...item,src:item.image,emoji:'⭐'}));
  const $=id=>document.getElementById(id),board=$('board'),movesEl=$('moves'),pairsEl=$('pairs'),preview=$('preview'),modal=$('match-modal'),matchImage=$('match-image'),matchSentence=$('match-sentence'),matchContinue=$('match-continue'),celebration=$('celebration'),playAgain=$('play-again'),confetti=$('confetti');
  let first=null,lock=false,moves=0,matched=0,game=0,lastDeck='',previewTimer=0,previewTick=0,celebrateAfter=false,voice=null;
  const shuffle=list=>{const out=[...list];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out};
  function pickVoice(){voice=speechSynthesis.getVoices().find(v=>/^en[-_]US$/i.test(v.lang||''))||null}if('speechSynthesis'in window){pickVoice();speechSynthesis.addEventListener('voiceschanged',pickVoice)}
  function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.92;if(voice)u.voice=voice;speechSynthesis.speak(u)}
  function makeCard(entry){const item=entry.item;const card=document.createElement('button');card.type='button';card.className='memory-card';card.dataset.id=item.id;card.dataset.copy=entry.copy;card.dataset.label=item.label;card.setAttribute('aria-label','Hidden picture card');const face=document.createElement('span');face.className='memory-card-picture';const img=new Image();img.src=item.src;img.alt=`${item.label} picture`;img.draggable=false;img.onerror=()=>{face.textContent=item.emoji;face.style.fontSize='3rem'};face.append(img);card.append(face);card.addEventListener('click',()=>flip(card));return card}
  function start(){game++;clearTimeout(previewTimer);clearInterval(previewTick);modal.hidden=true;celebration.hidden=true;confetti.replaceChildren();const picturePairs=pictures.flatMap(item=>[{item,copy:'a'},{item,copy:'b'}]);let deck,signature;do{deck=shuffle(picturePairs);signature=deck.map(x=>`${x.item.id}-${x.copy}`).join(',')}while(signature===lastDeck);lastDeck=signature;board.replaceChildren(...deck.map(makeCard));first=null;lock=false;moves=matched=0;movesEl.textContent='0';pairsEl.textContent='0';preview.disabled=false;preview.textContent='👀 Look for 3 Seconds'}
  function flip(card){if(lock||card.classList.contains('flipped')||card.classList.contains('matched'))return;card.classList.add('flipped');card.setAttribute('aria-label',`Revealed ${card.dataset.label}`);speak(card.dataset.label);if(!first){first=card;return}movesEl.textContent=String(++moves);if(first.dataset.id===card.dataset.id){lock=true;first.classList.add('matched');card.classList.add('matched');first=null;pairsEl.textContent=String(++matched);const id=card.dataset.id,currentGame=game;setTimeout(()=>{if(currentGame===game)showMatch(id)},450)}else{lock=true;const a=first,b=card,currentGame=game;first=null;setTimeout(()=>{if(currentGame!==game)return;a.classList.remove('flipped');b.classList.remove('flipped');a.setAttribute('aria-label','Hidden memory card');b.setAttribute('aria-label','Hidden memory card');lock=false},900)}}
  function showMatch(id){const item=pictures.find(x=>x.id===id);celebrateAfter=matched===pictures.length;matchImage.src=item.src;matchImage.alt=item.label;matchSentence.textContent=item.sentence;modal.hidden=false;speak(item.sentence);matchContinue.focus()}
  function showCelebration(){const colors=['#ff6fa5','#ffd93d','#4fc3f7','#b388ff','#7ed957','#ffa62b'];for(let i=0;i<70;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.left=`${Math.random()*100}%`;p.style.background=colors[i%colors.length];p.style.setProperty('--delay',`${Math.random()*-3}s`);p.style.setProperty('--fall-time',`${2.4+Math.random()*2}s`);p.style.setProperty('--drift',`${-90+Math.random()*180}px`);confetti.append(p)}celebration.hidden=false;playAgain.focus()}
  preview.addEventListener('click',()=>{if(lock||preview.disabled)return;const currentGame=game;lock=true;preview.disabled=true;board.querySelectorAll('.memory-card:not(.matched)').forEach(c=>c.classList.add('previewing'));let seconds=3;preview.textContent=`👀 Look: ${seconds}`;previewTick=setInterval(()=>{seconds--;if(seconds>0)preview.textContent=`👀 Look: ${seconds}`},1000);previewTimer=setTimeout(()=>{clearInterval(previewTick);if(currentGame!==game)return;board.querySelectorAll('.previewing').forEach(c=>c.classList.remove('previewing'));preview.disabled=false;preview.textContent='👀 Look for 3 Seconds';lock=false},3000)});
  $('restart').addEventListener('click',start);playAgain.addEventListener('click',start);matchContinue.addEventListener('click',()=>{modal.hidden=true;if('speechSynthesis'in window)speechSynthesis.cancel();if(celebrateAfter)showCelebration();else lock=false});start();
})();

