import '../../assets/navigation/gp-navigation.js?v=20260915-literacy&deploy=20260929-resource-fix-2';
import '../../assets/navigation/gp-sounds.js?deploy=20260929-resource-fix-2';
const pages=['page-01.html','video-activity.html','page-02.html','page-03.html','page-04.html','page-05.html'];
const file=location.pathname.split('/').pop(), index=pages.indexOf(file), tool=['tpr.html','flashcards.html','conversation.html'].includes(file);
const main=document.querySelector('main');
const nav=document.querySelector('gp-navigation');
nav.querySelector('[aria-label="Week Home"]').href='../#card-literacy';
const title='Week 1 — Where are the bees?';
const head=document.createElement('header');head.className='b-heading';
const heading=document.createElement('h1');heading.textContent=title;head.append(heading);
if(!tool){const tools=document.createElement('nav');tools.className='b-tools';tools.setAttribute('aria-label','Literacy tools');[['tpr.html','🎵 Week Song'],['flashcards.html','🃏 Flashcards'],['conversation.html','💬 Conversation']].forEach(([f,label])=>{const a=document.createElement('a');a.className='b-pill';a.textContent=label;a.href=f+'?return='+encodeURIComponent(file+'#lesson-focus');tools.append(a)});head.append(tools)}
main.prepend(head);
if(index>=0){const pager=document.createElement('nav');pager.className='b-pages';pager.setAttribute('aria-label','Literacy pages');pager.innerHTML=`<strong>Page ${index+1} of 6</strong><div>${pages.map((p,i)=>`<a href="${p}#lesson-focus" aria-label="Page ${i+1} of 6" ${i===index?'aria-current="page"':''}>${i+1}</a>`).join('')}</div>`;head.after(pager)}
if(tool){let back='page-01.html';try{const u=new URL(new URLSearchParams(location.search).get('return')||back,location.href);if(u.origin===location.origin&&u.pathname.slice(0,u.pathname.lastIndexOf('/')+1)===location.pathname.slice(0,location.pathname.lastIndexOf('/')+1)&&pages.includes(u.pathname.split('/').pop()))back=u.pathname.split('/').pop()}catch{}const a=document.createElement('a');a.className='b-pill b-return';a.textContent='← Back to Page '+(pages.indexOf(back)+1);a.href=back+'#lesson-focus';const marker=document.createComment('mobile return');main.prepend(marker);const mq=matchMedia('(min-width:721px)');function place(){a.classList.toggle('b-return-mobile',!mq.matches);if(mq.matches)nav.querySelector('.gp-navigation__links').append(a);else marker.after(a)}mq.addEventListener('change',place);place()}
const stage=document.querySelector('.b-stage');
if(stage){const frame=document.createElement('section');frame.className='b-workbook-frame';frame.id='lesson-focus';stage.removeAttribute('id');stage.before(frame);frame.append(stage,document.querySelector('.b-controls'));}
function centerWorkbook(){if(location.hash!=='#lesson-focus')return;const frame=document.getElementById('lesson-focus');if(!frame)return;frame.scrollIntoView({block:'center',behavior:'auto'});const bottom=nav.getBoundingClientRect().bottom;if(frame.getBoundingClientRect().top<bottom+12)window.scrollBy(0,frame.getBoundingClientRect().top-bottom-12)}
addEventListener('load',centerWorkbook);addEventListener('pageshow',centerWorkbook);addEventListener('hashchange',centerWorkbook);document.fonts?.ready.then(centerWorkbook);
if(stage){
const page=Number(document.body.dataset.page), layer=document.querySelector('.b-start'), status=document.querySelector('.b-status');
const art=stage.querySelector('img'); let started=false,finished=false,timer,selected=null;const completed=new Set();
function say(text,done){if(!('speechSynthesis'in window)){done?.();return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.85;let called=false;const finish=()=>{if(called)return;called=true;done?.()};u.onend=finish;u.onerror=finish;if(done)setTimeout(finish,7000);speechSynthesis.speak(u)}
function button(label,x,y,w,h,cls='b-hotspot'){const b=document.createElement('button');b.type='button';b.className=cls;b.setAttribute('aria-label',label);b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;stage.insertBefore(b,layer);return b}
function wrong(b){b.classList.remove('is-wrong');void b.offsetWidth;b.classList.add('is-wrong');status.textContent='Try again.';say('Try again.');setTimeout(()=>b.classList.remove('is-wrong'),400)}
const dialog=document.querySelector('[data-completion]'),video=dialog.querySelector('video'),close=dialog.querySelector('[data-close]');let lastFocus;
function dismiss(){video.pause();dialog.hidden=true;document.body.classList.remove('completion-open');lastFocus?.focus()}
function win(){if(finished)return;finished=true;timer=setTimeout(()=>{lastFocus=document.activeElement;dialog.hidden=false;document.body.classList.add('completion-open');video.currentTime=0;video.controls=true;video.play().catch(()=>{});close.focus()},500)}
close.onclick=dismiss;dialog.querySelector('[data-try-again]').onclick=()=>{dismiss();reset()};dialog.addEventListener('keydown',e=>{if(e.key==='Escape')dismiss();if(e.key==='Tab'){const controls=[close,dialog.querySelector('[data-try-again]')];e.preventDefault();controls[document.activeElement===controls[0]?1:0].focus()}});
function hit(b,id,total){if(!started||finished||completed.has(id))return;completed.add(id);b.classList.add('is-correct');b.setAttribute('aria-pressed','true');status.textContent=completed.size+' of '+total;if(completed.size===total)win()}
let resetExtra=()=>{};
if(page===2){
let value=0;
const bees=[];
[[36.5,39,7,9],[67,48,8,10],[20,62,7,9],[43,60.5,7,9],[57.5,61.5,7.5,9.5],[73.5,64,8,10]].forEach(([x,y,w,h],i)=>{const bee=button('Mark bee '+(i+1),x,y,w,h,'b-hotspot b-bee');bee.setAttribute('aria-pressed','false');bee.onclick=()=>{if(!started||finished)return;const marked=bee.getAttribute('aria-pressed')!=='true';bee.setAttribute('aria-pressed',String(marked));bee.classList.toggle('is-counted',marked)};bees.push(bee)});
const sentence=document.createElement('div');sentence.className='b-count-sentence';
sentence.innerHTML='<span>There are</span><span class="count-selector" aria-label="Choose a number from zero to ten"><button type="button" data-count-up aria-label="Increase number">▲</button><output data-count-value aria-live="polite">0</output><button type="button" data-count-down aria-label="Decrease number">▼</button><button type="button" class="count-go" data-count-go>Go</button></span><span>bees in the garden.</span>';
stage.insertBefore(sentence,layer);
const selector=sentence.querySelector('.count-selector'),output=sentence.querySelector('output'),up=sentence.querySelector('[data-count-up]'),down=sentence.querySelector('[data-count-down]'),go=sentence.querySelector('[data-count-go]');
function update(n){value=Math.max(0,Math.min(10,n));output.textContent=value;output.setAttribute('aria-label','Selected number: '+value);selector.classList.remove('is-wrong');up.disabled=finished||value===10;down.disabled=finished||value===0;}
up.onclick=()=>{if(started&&!finished)update(value+1)};down.onclick=()=>{if(started&&!finished)update(value-1)};
go.onclick=()=>{if(!started||finished)return;if(value!==6){wrong(selector);return}selector.classList.add('is-correct');status.textContent='There are 6 bees in the garden.';win();up.disabled=down.disabled=go.disabled=true};
resetExtra=()=>{selector.classList.remove('is-correct','is-wrong');bees.forEach(bee=>{bee.classList.remove('is-counted');bee.setAttribute('aria-pressed','false')});update(0)};
}
if(page===3){const words=[['bench',5,35,17,21,5.5,56.3],['trees',5,66.5,17,21,5.5,87.5],['lamp',78,35,17,21,79,56.3],['people',78,66.5,17,21,79,87.5]],letters=[];const slots=[[39,40],[52,40],[39,75],[52,75]];
words.forEach(([word,x,y,w,h,bx,by])=>{const blank=document.createElement('span');blank.className='b-blank';blank.style.cssText=`left:${bx}%;top:${by}%;width:15.5%;height:5.8%`;blank.dataset.word=word;blank.textContent='_'+word.slice(1);stage.insertBefore(blank,layer);const b=button('Complete '+word,x,y,w,h);b.dataset.word=word;b.onclick=()=>{if(!started||finished)return;say(word);if(!selected||completed.has(word))return;if(selected.textContent===word[0]){blank.textContent=word;selected.disabled=true;selected.classList.remove('selected');selected=null;hit(b,word,4)}else wrong(selected)};blank.tabIndex=0;blank.setAttribute('role','button');blank.setAttribute('aria-label','Fill missing letter for '+word);blank.onclick=()=>b.click();blank.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click()}};const speaker=button('Hear '+word,x+12,y+18,5,6,'b-speaker');speaker.textContent='🔊';speaker.onclick=()=>say(word);blank.addEventListener('dragover',e=>e.preventDefault());blank.addEventListener('drop',e=>{e.preventDefault();b.click()});b.addEventListener('dragover',e=>e.preventDefault());b.addEventListener('drop',e=>{e.preventDefault();b.click()})});
['b','t','l','p'].forEach(letter=>{const b=button('Choose letter '+letter,0,0,9,12,'b-letter');b.textContent=letter;b.draggable=true;const choose=()=>{if(!started||b.disabled)return;letters.forEach(x=>x.classList.remove('selected'));selected=b;b.classList.add('selected');say(letter)};b.onclick=choose;b.ondragstart=choose;letters.push(b)});
resetExtra=()=>{const shuffled=slots.map(p=>({p,n:Math.random()})).sort((a,b)=>a.n-b.n);letters.forEach((b,i)=>{b.style.left=shuffled[i].p[0]+'%';b.style.top=shuffled[i].p[1]+'%';b.disabled=false;b.classList.remove('selected')});stage.querySelectorAll('.b-blank').forEach(b=>b.textContent='_'+b.dataset.word.slice(1));selected=null};}
if(page===4){[['grass',14,33],['lamp',40,33],['flowers',66,33],['bench',14,64],['trees',40,64],['classroom',66,64]].forEach(([word,x,y])=>{const b=button('Choose '+word,x,y,21,27);b.onclick=()=>{if(!started||finished)return;say(word);if(word==='classroom')wrong(b);else hit(b,word,5)}})}
if(page===5){const path=[[31.5,79.5],[39,79.5],[39,72],[33,72],[33,65.5],[44.5,65.5],[44.5,72.8],[56,72.8],[56,58],[66.7,58],[66.7,51],[70.4,51]];let step=0,drag=false;const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 100 100');svg.setAttribute('preserveAspectRatio','none');svg.classList.add('b-trace');const line=document.createElementNS(svg.namespaceURI,'polyline');line.setAttribute('fill','none');line.setAttribute('stroke','#218df0');line.setAttribute('stroke-width','.7');line.setAttribute('stroke-linecap','round');line.setAttribute('stroke-linejoin','round');svg.append(line);stage.insertBefore(svg,layer);const dot=document.createElement('span');dot.className='b-maze-dot';stage.insertBefore(dot,layer);const area=document.createElement('div');area.className='b-maze';area.tabIndex=0;area.setAttribute('role','application');area.setAttribute('aria-label','Trace from the blue dot to the park gate. Drag or tap along the corridor.');stage.insertBefore(area,layer);
const distance=(p,a,b)=>{const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p[0]-a[0])*dx+(p[1]-a[1])*dy)/(dx*dx+dy*dy)));return Math.hypot(p[0]-a[0]-t*dx,p[1]-a[1]-t*dy)};
function paint(p=path[step]){line.setAttribute('points',[...path.slice(0,step+1),p].map(p=>p.join(',')).join(' '));dot.style.left=p[0]+'%';dot.style.top=p[1]+'%'}
function move(e){if(!started||finished||step>=path.length-1)return;const r=stage.getBoundingClientRect(),p=[(e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100];if(distance(p,path[step],path[step+1])>1.8)return;paint(p);if(Math.hypot(p[0]-path[step+1][0],p[1]-path[step+1][1])<1.8){step++;paint();if(step===path.length-1)win()}}
area.onpointerdown=e=>{drag=true;area.setPointerCapture(e.pointerId);move(e)};area.onpointermove=e=>{if(drag)move(e)};area.onpointerup=()=>drag=false;area.onpointercancel=()=>drag=false;area.onkeydown=e=>{if(!started||finished||!e.key.startsWith('Arrow'))return;e.preventDefault();const a=path[step],b=path[step+1],key=Math.abs(b[0]-a[0])>Math.abs(b[1]-a[1])?(b[0]>a[0]?'ArrowRight':'ArrowLeft'):(b[1]>a[1]?'ArrowDown':'ArrowUp');if(e.key===key){step++;paint();if(step===path.length-1)win()}};resetExtra=()=>{step=0;drag=false;paint()};}
function reset(){if('speechSynthesis'in window)speechSynthesis.cancel();clearTimeout(timer);started=false;finished=false;completed.clear();stage.querySelectorAll('.b-hotspot').forEach(b=>{b.classList.remove('is-correct','is-wrong');b.setAttribute('aria-pressed','false')});resetExtra();stage.querySelectorAll('button:not(.b-start button)').forEach(b=>b.disabled=true);layer.hidden=false;status.textContent='';layer.querySelector('button').focus({preventScroll:true})}
layer.querySelector('button').onclick=()=>{layer.hidden=true;say({2:'How many bees are in the garden? Choose a number, then press Go.',3:'Which letter is missing?',4:'Circle the things at the park.',5:'Help her to the park gate.'}[page],()=>{if(layer.hidden){started=true;stage.querySelectorAll('button').forEach(b=>b.disabled=false);const down=stage.querySelector('[data-count-down]');if(down)down.disabled=true}})};document.querySelector('[data-reset]').onclick=reset;reset();
window.addEventListener('pagehide',()=>{clearTimeout(timer);video.pause();if('speechSynthesis'in window)speechSynthesis.cancel()});
}
