import {revealNextAction,hideNextAction} from "../assets/navigation/gp-navigation.js?v=20260902-4";
const challenges=[
 {page:2,title:"Which sport are they playing?",prompt:"Look at the court and racket. Choose the sport.",choices:["soccer","basketball","golf","tennis"],answer:"tennis",good:"Goal! The racket and net show tennis."},
 {page:3,title:"Find one missing first letter",prompt:"Supplemental check: Which letter completes _occer?",choices:["b","v","s","p"],answer:"s",good:"Super! S makes soccer."},
 {page:4,title:"Read the scoreboard",prompt:"The home team has 2. The away team has 1. Who lost?",choices:["Home team","Away team"],answer:"Away team",good:"That’s right. 1 is fewer than 2, so the away team lost."},
 {page:5,title:"Count the teams",prompt:"How many sports teams are in the pictures?",choices:["2","3","4"],answer:"3",good:"Great counting! There are 3 sports teams."},
 {page:6,title:"Match one sports word",prompt:"Supplemental check: Which picture matches “soccer”?",choices:["Left picture","Right picture"],answer:"Left picture",good:"Correct! The left picture shows children playing soccer."},
 {page:7,title:"Practice one sentence",prompt:"Choose the sentence that matches the soccer player.",choices:["I like soccer.","I like volleyball."],answer:"I like soccer.",good:"Nice reading!"},
 {page:8,title:"Match one sports word",prompt:"Supplemental check: Which picture matches “basketball”?",choices:["Left picture","Right picture"],answer:"Right picture",good:"Correct! The right picture shows basketball."},
 {page:9,title:"Practice one sentence",prompt:"Choose the sentence that matches the baseball player.",choices:["I like basketball.","I like baseball."],answer:"I like baseball.",good:"Home run!"}
];
let index=0;const box=document.querySelector("#challenge"),next=document.querySelector("#next-button"),bar=document.querySelector("#progress-bar"),label=document.querySelector("#step-label"),map=document.querySelector("#page-map");
function render(){const c=challenges[index];hideNextAction(next);label.textContent=`Challenge ${index+1} of ${challenges.length}`;map.textContent=`Activity ${index+1}`;bar.style.width=`${index/challenges.length*100}%`;box.innerHTML=`<div class="challenge-head"><div><h1>${c.title}</h1><p class="instruction">${c.prompt}</p></div><button class="audio-placeholder" type="button" disabled title="Recorded audio will be added here" aria-label="Recorded audio coming later">🔇</button></div><div class="activity-grid"><figure class="book-frame"><img src="https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-a/assets/book/week-1/page-${c.page}.png" alt="Level A Month 8 activity artwork"></figure><div class="quiz-panel"><div class="choices">${c.choices.map(x=>`<button class="choice" type="button" data-value="${x}">${x}</button>`).join("")}</div><p class="feedback" id="feedback">Choose one answer.</p><p class="note">🔊 Recorded narration placeholder — no browser voice is used.</p></div></div>`;box.querySelectorAll(".choice").forEach(button=>button.addEventListener("click",()=>check(button,c)));scrollTo({top:0,behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})}
function check(button,c){const feedback=box.querySelector("#feedback");if(button.dataset.value===c.answer){box.querySelectorAll(".choice").forEach(b=>{b.disabled=true;b.classList.toggle("correct",b===button)});feedback.textContent=`⭐ ${c.good}`;feedback.className="feedback good";next.textContent=index===challenges.length-1?"Finish Lesson 🏅":"Next Challenge →";revealNextAction(next)}else{button.classList.add("wrong");feedback.textContent="Try again. Look closely and choose again.";feedback.className="feedback try";setTimeout(()=>button.classList.remove("wrong"),350)}}
next.addEventListener("click",()=>{if(index<challenges.length-1){index++;render()}else{bar.style.width="100%";label.textContent="8 of 8 complete";map.textContent="Activities 1–8";hideNextAction(next);box.innerHTML=`<div class="finish"><img src="https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-a/assets/ui/sport-medal-3d.webp" alt="Gold medal"><h1>Sports Stadium Champion!</h1><p class="instruction">You completed the supplemental Week 1 web checks.</p><a class="primary" href="../week-1.html">🏠 Return to Week 1 Home</a></div>`}});render();
