import { natureItems, shuffle } from "./game-data.js?deploy=20261003-level-c-tpr-and-lesson-tools-v11";

const app=document.querySelector("#game-app"),gameType=document.body.dataset.game;
if(gameType==="wheel"&&!window.SpinWheelBonus){await new Promise(resolve=>{const script=document.createElement("script");script.src="/LevelC_M8/apps/level-b/games/spin-wheel-bonus.js?v=20260907-1&deploy=20261003-level-c-tpr-and-lesson-tools-v11";script.onload=script.onerror=resolve;document.head.append(script);});}
const titles={memory:["🧠","Memory Game"],wheel:["🎡","Spin the Wheel"],matching:["🧩","Picture Match"],pick:["☝️","Pick the Right One"]};
if(app&&titles[gameType]){
  const [icon,title]=titles[gameType];
  app.innerHTML=`<header class="play-header"><h1>${icon} ${title}</h1><p>Week 1 Nature Review · Park, Garden, Yard, and Cave</p></header><section id="play-area"></section>`;
  const playArea=app.querySelector("#play-area");
  const feedback=(message,state="")=>{const node=playArea.querySelector("#game-feedback");if(node){node.textContent=message;node.className=`game-feedback ${state}`.trim();}};

  function renderMemory(){
    let active=[],first=null,locked=false,moves=0,pairs=0;
    playArea.innerHTML=`<div class="game-toolbar"><span class="score-chip">Moves: <b id="moves">0</b></span><span class="score-chip">Pairs: <b id="pairs">0</b>/6</span><button class="game-button orange" id="new-game" type="button">🔄 New Game</button></div><section class="game-board"><div class="memory-board" id="memory-board"></div><p id="game-feedback" class="game-feedback" aria-live="polite">Find two matching nature cards.</p></section>`;
    const board=playArea.querySelector("#memory-board");
    function start(){active=shuffle(natureItems).slice(0,6);first=null;locked=false;moves=0;pairs=0;playArea.querySelector("#moves").textContent="0";playArea.querySelector("#pairs").textContent="0";feedback("Find two matching nature cards.");const deck=shuffle(active.flatMap(item=>[item,item]));board.innerHTML="";deck.forEach((item,index)=>{const button=document.createElement("button");button.type="button";button.className="memory-tile";button.dataset.id=item.id;button.dataset.copy=String(index);button.setAttribute("aria-label","Hidden memory card");button.innerHTML=`<span class="tile-cover">?</span><span class="tile-answer"><span>${item.icon}</span><small>${item.label}</small></span>`;button.addEventListener("click",()=>flip(button,item));board.append(button);});}
    function flip(button,item){if(locked||button.classList.contains("is-open")||button.classList.contains("is-matched"))return;button.classList.add("is-open");button.setAttribute("aria-label",item.label);if(!first){first=button;feedback(`You found ${item.label}. Find its match!`);return;}locked=true;moves+=1;playArea.querySelector("#moves").textContent=String(moves);if(first.dataset.id===button.dataset.id){first.classList.replace("is-open","is-matched");button.classList.replace("is-open","is-matched");pairs+=1;playArea.querySelector("#pairs").textContent=String(pairs);first=null;locked=false;if(pairs===6){feedback("Wonderful! You found all six nature pairs.","good");}else feedback(`Great match! ${item.sentence}`,"good");return;}const previous=first;first=null;feedback("Those cards are different. Remember them and try again!","try");setTimeout(()=>{previous.classList.remove("is-open");button.classList.remove("is-open");previous.setAttribute("aria-label","Hidden memory card");button.setAttribute("aria-label","Hidden memory card");locked=false;},650);}
    playArea.querySelector("#new-game").addEventListener("click",start);start();
  }

  function renderRounds(kind){
    let deck=[],round=0,score=0,locked=false;
    const isMatching=kind==="matching";
    playArea.innerHTML=`<div class="game-toolbar"><span class="score-chip">Round: <b id="round">1</b>/8</span><span class="score-chip">Score: <b id="score">0</b></span><button class="game-button orange" id="new-game" type="button">🔄 New Round</button></div><section class="game-board"><h2 id="prompt" class="game-prompt"></h2><div id="round-picture" class="pick-picture" ${isMatching?'hidden':''}></div><div id="round-choices"></div><p id="game-feedback" class="game-feedback" aria-live="polite"></p><div class="launch-row"><button id="next-round" class="game-button green" type="button" hidden>Next →</button></div></section>`;
    function start(){deck=shuffle(natureItems).slice(0,8);round=0;score=0;playArea.querySelector("#score").textContent="0";render();}
    function render(){locked=false;const item=deck[round];playArea.querySelector("#round").textContent=String(round+1);playArea.querySelector("#next-round").hidden=true;const choices=playArea.querySelector("#round-choices");choices.className=isMatching?"choice-grid":"phrase-grid";choices.innerHTML="";if(isMatching){playArea.querySelector("#prompt").textContent=item.sentence;const options=shuffle([item,...shuffle(natureItems.filter(other=>other.id!==item.id)).slice(0,2)]);options.forEach(option=>addChoice(choices,option.icon,option.id===item.id,option.label));feedback("Choose the picture that matches the source sentence.");}else{playArea.querySelector("#prompt").textContent=`Which phrase matches this ${item.place.toLowerCase()} picture?`;const picture=playArea.querySelector("#round-picture");picture.textContent=item.icon;picture.setAttribute("aria-label",item.label);const wrong=shuffle(natureItems.filter(other=>other.id!==item.id))[0];shuffle([{text:item.label,ok:true},{text:wrong.label,ok:false}]).forEach(option=>addChoice(choices,option.text,option.ok,option.text));feedback("Pick the right phrase.");}}
    function addChoice(container,text,correct,label){const button=document.createElement("button");button.type="button";button.className=isMatching?"picture-choice":"phrase-choice";button.setAttribute("aria-label",label);button.innerHTML=isMatching?`<span aria-hidden="true">${text}</span><small>${label}</small>`:text;button.addEventListener("click",()=>choose(button,correct));container.append(button);}
    function choose(button,correct){if(locked)return;if(!correct){button.classList.add("is-wrong");feedback("Good try. Look closely and choose again.","try");setTimeout(()=>button.classList.remove("is-wrong"),420);return;}locked=true;button.classList.add("is-correct");playArea.querySelectorAll("#round-choices button").forEach(choice=>choice.disabled=true);score+=1;playArea.querySelector("#score").textContent=String(score);feedback(`Correct! ${deck[round].sentence}`,"good");const next=playArea.querySelector("#next-round");next.textContent=round===deck.length-1?"Finish 🏆":"Next →";next.hidden=false;}
    playArea.querySelector("#next-round").addEventListener("click",()=>{if(round===deck.length-1){playArea.querySelector(".game-board").innerHTML=`<div class="complete-panel"><span>🏆</span><h2>Nature Expert!</h2><p>You completed all eight rounds.</p><button class="game-button green" id="again" type="button">Play Again</button></div>`;playArea.querySelector("#again").addEventListener("click",()=>renderRounds(kind));return;}round+=1;render();});playArea.querySelector("#new-game").addEventListener("click",start);start();
  }

  function renderWheel(){
    let spinning=false,selected=null,wheelTurns=0;
    const wheelItems=shuffle(natureItems).slice(0,8);
    const bonusIcons={"spin-again":"🔄","super-star":"⭐",boom:"💥"};
    const bonusItems=(window.SpinWheelBonus?.createSegments?.()||[
      {bonus:"spin-again",label:"Spin Again",sentence:"Spin again!"},
      {bonus:"super-star",label:"Super Star",sentence:"Super Star! You are amazing!"},
      {bonus:"boom",label:"Boom",sentence:"Boom! Try again next time!"}
    ]).map(item=>({...item,icon:bonusIcons[item.bonus]}));
    const segments=[...wheelItems,...bonusItems];
    playArea.innerHTML=`<section class="game-board"><div class="wheel-area"><div class="wheel-wrap"><span class="wheel-pointer" aria-hidden="true">▼</span><div class="nature-wheel" id="wheel" aria-label="Nature review wheel"></div><span class="wheel-hub" aria-hidden="true">🌿</span></div><div><div class="game-toolbar"><button class="game-button orange" id="spin" type="button">Spin</button><button class="game-button green" id="stop" type="button" hidden>Stop</button></div><div class="wheel-result" id="wheel-result"><div><span class="result-icon" aria-hidden="true">🎡</span><strong>Spin, then press Stop!</strong><p>A nature card or Month 7-style bonus will appear.</p></div></div><p id="game-feedback" class="game-feedback" aria-live="polite">Ready to spin.</p></div></div></section>`;
    const wheel=playArea.querySelector("#wheel"),spin=playArea.querySelector("#spin"),stop=playArea.querySelector("#stop"),result=playArea.querySelector("#wheel-result");
    const colors=["#ff8a80","#80d8ff","#b9f6ca","#ffd180","#ea80fc","#ffff8d","#84ffff","#ff9e80","#56d4df","#ffd43b","#a56bf2"];
    const slice=360/segments.length;
    wheel.style.background=`conic-gradient(${colors.map((color,index)=>`${color} ${index*slice}deg ${(index+1)*slice}deg`).join(",")})`;
    wheel.setAttribute("aria-label",`Wheel with ${segments.map(item=>item.label).join(", ")}`);
    segments.forEach((item,index)=>{const angle=(index+.5)*Math.PI*2/segments.length;const label=document.createElement("span");label.innerHTML=`<b>${item.icon}</b>${item.bonus?`<small>${item.label}</small>`:""}`;label.title=item.label;label.setAttribute("aria-hidden","true");label.style.cssText=`position:absolute;left:${50+36*Math.sin(angle)}%;top:${50-36*Math.cos(angle)}%;transform:translate(-50%,-50%);font-size:${item.bonus?"1.35rem":"2rem"};max-width:74px;text-align:center;line-height:.88`;wheel.append(label);});
    spin.addEventListener("click",()=>{if(spinning)return;spinning=true;selected=null;wheel.classList.add("is-spinning");spin.hidden=true;stop.hidden=false;result.innerHTML='<div><span class="result-icon">🌪️</span><strong>Wheel spinning…</strong><p>Press Stop when you are ready.</p></div>';feedback("The wheel is spinning. Press Stop!","");});
    stop.addEventListener("click",()=>{if(!spinning)return;spinning=false;wheel.classList.remove("is-spinning");stop.hidden=true;spin.hidden=false;const selectedIndex=Math.floor(Math.random()*segments.length);selected=segments[selectedIndex];wheelTurns+=3;wheel.style.transform=`rotate(${wheelTurns*360-(selectedIndex+.5)*slice}deg)`;if(selected.bonus){result.innerHTML=`<div><span class="result-icon">${selected.icon}</span><strong>${selected.label}!</strong><p>${selected.sentence}</p></div>`;feedback(`Bonus segment: ${selected.label}!`,selected.bonus==="boom"?"try":"good");window.SpinWheelBonus?.show?.(selected,{onSpinAgain:()=>spin.click(),onClose:()=>spin.focus({preventScroll:true})});return;}result.innerHTML=`<div><span class="result-icon">${selected.icon}</span><strong>${selected.label}</strong><p>${selected.sentence}</p><small>${selected.place}</small></div>`;feedback(`Nature segment: ${selected.label}. ${selected.sentence}`,"good");});
  }

  if(gameType==="memory")renderMemory();else if(gameType==="wheel")renderWheel();else renderRounds(gameType);
}
