export const gameMeta = { week: 2, topic: "Insect Parts", review: "Bee and Butterfly Parts", wheelIcon: "🐝", completion: "Insect Parts Expert!" };
const root = "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/flashcards/week-2/speech";
export const gameItems = [
  { id: "bee-abdomen", memoryKey: "abdomen", label: "bee abdomen", sentence: "The bee has one abdomen.", group: "Bee", wheelIcon: "🐝", image: `${root}/bee-abdomen-v2.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/bee-abdomen.png?v=insect-rings-v3&asset=c0507673b468" },
  { id: "bee-antennae", memoryKey: "antennae", label: "bee antennae", sentence: "The bee has two antennae.", group: "Bee", wheelIcon: "🐝", image: `${root}/bee-antennae-v2.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/bee-antennae.png?v=insect-rings-v3&asset=dafb8caec196" },
  { id: "bee-wings", memoryKey: "wings", label: "bee wings", sentence: "The bee has four wings.", group: "Bee", wheelIcon: "🪽", image: `${root}/bee-wings-v2.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/bee-wings.png?v=insect-rings-v3&asset=1ab61804788e" },
  { id: "bee-eyes", memoryKey: "eyes", label: "bee eyes", sentence: "The bee has five eyes.", group: "Bee", wheelIcon: "👀", image: `${root}/bee-eyes-v2.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/bee-eyes.png?v=insect-rings-v3&asset=6e70850250ac" },
  { id: "bee-legs", memoryKey: "legs", label: "bee legs", sentence: "The bee has six legs.", group: "Bee", wheelIcon: "🐝", image: `${root}/bee-legs-v2.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/bee-legs.png?v=insect-rings-v3&asset=fd9fd19bdaed" },
  { id: "butterfly-antennae", memoryKey: "antennae", label: "butterfly antennae", sentence: "The butterfly has antennae.", group: "Butterfly", wheelIcon: "🦋", image: `${root}/butterfly-antennae-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/butterfly-antennae.png?v=insect-rings-v3&asset=8215dac0ca18", literacy: false },
  { id: "butterfly-eyes", memoryKey: "eyes", label: "butterfly eyes", sentence: "The butterfly has eyes.", group: "Butterfly", wheelIcon: "👀", image: `${root}/butterfly-eyes-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/butterfly-eyes.png?v=insect-rings-v3&asset=ce68d8871a5d", literacy: false },
  { id: "butterfly-wings", memoryKey: "wings", label: "butterfly wings", sentence: "The butterfly has wings.", group: "Butterfly", wheelIcon: "🪽", image: `${root}/butterfly-wings-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/butterfly-wings.png?v=insect-rings-v3&asset=9083f5e7a30e", literacy: false },
  { id: "butterfly-legs", memoryKey: "legs", label: "butterfly legs", sentence: "The butterfly has legs.", group: "Butterfly", wheelIcon: "🦋", image: `${root}/butterfly-legs-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/butterfly-legs.png?v=insect-rings-v3&asset=3970258296a0", literacy: false },
  { id: "butterfly-abdomen", memoryKey: "abdomen", label: "butterfly abdomen", sentence: "The butterfly has an abdomen.", group: "Butterfly", wheelIcon: "🦋", image: `${root}/butterfly-abdomen-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-2/butterfly-abdomen.png?v=insect-rings-v3&asset=33490855709e", literacy: false }
];
export function shuffle(items) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const other = Math.floor(Math.random() * (index + 1)); [copy[index], copy[other]] = [copy[other], copy[index]]; } return copy; }
