export const gameMeta = { week: 3, topic: "Animals That Hunt and Fly", review: "Animals That Hunt and Fly", wheelIcon: "🦅", completion: "Wildlife Expert!" };
const animalRoot = "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/literacy/week-3/reading";
export const gameItems = [
  { id: "eagle", label: "eagle hunts and flies", sentence: "An eagle hunts and flies.", group: "Wildlife", wheelIcon: "🦅", image: `${animalRoot}/eagle-landscape-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-3/eagle.png" },
  { id: "lion", label: "lion hunts on land", sentence: "A lion hunts on land.", group: "Wildlife", wheelIcon: "🦁", image: `${animalRoot}/lion-landscape-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-3/lion.png" },
  { id: "falcon", label: "falcon hunts from the sky", sentence: "A falcon hunts from the sky.", group: "Wildlife", wheelIcon: "🦅", image: `${animalRoot}/falcon-landscape-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-3/falcon.png" },
  { id: "owl", label: "owl flies in the dark", sentence: "An owl flies in the dark.", group: "Wildlife", wheelIcon: "🦉", image: `${animalRoot}/owl-landscape-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-3/owl.png" },
  { id: "butterfly", label: "butterfly flies in the day", sentence: "A butterfly flies in the day.", group: "Wildlife", wheelIcon: "🦋", image: `${animalRoot}/butterfly-landscape-v1.png`, gameImage: "https://pub-aa69c309a877446c857c4f2564279578.r2.dev/language-m8/apps/level-c/assets/games/cutouts/week-3/butterfly.png" }
];
export function shuffle(items) { const copy = [...items]; for (let index = copy.length - 1; index > 0; index -= 1) { const other = Math.floor(Math.random() * (index + 1)); [copy[index], copy[other]] = [copy[other], copy[index]]; } return copy; }
